steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
    cp $(Build.SourcesDirectory)/*.vsix $(Build.ArtifactStagingDirectory)
  displayName: 'Compile and package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ado-extension'
    publishLocation: 'Container'
